name: Test

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Node install
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Dependencies
      run: yarn install

    - name: Build
      run: yarn test
